config/routes.rb
  Rails.application.routes.draw do
  resources :materios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/materio.rb
class Materio < ApplicationRecord
	has_one_attached :drop_box
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/materios_controller.rb
class MateriosController < ApplicationController
  before_action :set_materio, only: %i[ show edit update destroy ]

  # GET /materios or /materios.json
  def index
    @materios = Materio.all
  end

  # GET /materios/1 or /materios/1.json
  def show
  end

  # GET /materios/new
  def new
    @materio = Materio.new
  end

  # GET /materios/1/edit
  def edit
  end

  # POST /materios or /materios.json
  def create
    @materio = Materio.new(materio_params)

    respond_to do |format|
      if @materio.save
        format.html { redirect_to @materio, notice: "Materio was successfully created." }
        format.json { render :show, status: :created, location: @materio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @materio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materios/1 or /materios/1.json
  def update
    respond_to do |format|
      if @materio.update(materio_params)
        format.html { redirect_to @materio, notice: "Materio was successfully updated." }
        format.json { render :show, status: :ok, location: @materio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @materio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materios/1 or /materios/1.json
  def destroy
    @materio.destroy
    respond_to do |format|
      format.html { redirect_to materios_url, notice: "Materio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_materio
      @materio = Materio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def materio_params
      params.require(:materio).permit(:your_name, :your_email, :Company, :apr_budget, :optional, :drop_box)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materios_helper.rb
module MateriosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InternAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <link rel="stylesheet" type="text/css" href="newstyles.css">
  <link rel="capture.JPG" type="image">
  <bgcolor="blue">
  <table  width="80%" cellspacing="5px" align="right">
    <tr>
      <td rowspan="2" valign="top" width="60%">
        <img src="capture.JPG" height="200px" >

        <h1 style="color: blue;" >Materio</h1>
                                <big><b>Contact Us</b></big>
        <p><b>Looking for a design partner?</b></p>
                                <p><b>You found</b></p>

      </td>
      <td class="block"><h2>Register here</h2></td>
      <td><h2>Login</h2></td>
    </tr>
        <%= yield %>
  </body>
</html>

app/views/materios/_form.html.erb
<%= form_with(model: materio) do |form| %>
  <% if materio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(materio.errors.count, "error") %> prohibited this materio from being saved:</h2>

      <ul>
        <% materio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :your_name %>
    <%= form.text_field :your_name %>
  </div>

  <div class="field">
    <%= form.label :your_email %>
    <%= form.text_field :your_email %>
  </div>

  <div class="field">
    <%= form.label :Company %>
    <%= form.text_field :Company %>
  </div>

  <div class="field">
    <%= form.label :apr_budget %>
    <%= form.text_field :apr_budget %>
  </div>

  <div class="field">
    <%= form.label :optional %>
    <%= form.text_area :optional %>
  </div>

   <div class="field">
    <%= form.label :drop_box %>
    <%= form.file_field :drop_box %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/materios/edit.html.erb
<h1>Editing Materio</h1>

<%= render 'form', materio: @materio %>
<%= link_to 'Show', @materio %> |
<%= link_to 'Back', materios_path %>

app/views/materios/index.html.erb
<p id="notice"><%= notice %></p>


<table>
  <thead>
    <tr>
      <th>Your name</th>
      <th>Your email</th>
      <th>Company</th>
      <th>Apr budget</th>
      <th>Optional</th>
      <th>Drop box</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materios.each do |materio| %>
      <tr>
        <td><%= materio.your_name %></td>
        <td><%= materio.your_email %></td>
        <td><%= materio.Company %></td>
        <td><%= materio.apr_budget %></td>
        <td><%= materio.optional %></td>
        <td><%= materio.drop_box %></td>
        <td><%= link_to 'Show', materio %></td>
        <td><%= link_to 'Edit', edit_materio_path(materio) %></td>
        <td><%= link_to 'Destroy', materio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Materio', new_materio_path %>

app/views/materios/new.html.erb
<h1>New Materio</h1>

<%= render 'form', materio: @materio %>

<%= link_to 'Back', materios_path %>

app/views/materios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Your name:</strong>
  <%= @materio.your_name %>
</p>

<p>
  <strong>Your email:</strong>
  <%= @materio.your_email %>
</p>

<p>
  <strong>Company:</strong>
  <%= @materio.Company %>
</p>

<p>
  <strong>Apr budget:</strong>
  <%= @materio.apr_budget %>
</p>

<p>
  <strong>Optional:</strong>
  <%= @materio.optional %>
</p>

<p>
  <strong>Drop box:</strong>
  <%= @materio.drop_box %>
</p>


<%= link_to 'Edit', edit_materio_path(@materio) %> |
<%= link_to 'Back', materios_path %>